install! 'cocoapods',
         :generate_multiple_pod_projects => true,
         :incremental_installation => true,
         :preserve_pod_file_structure => true

pod 'Forge', :git => 'git@github.com:Hi-Rez/Forge.git'
pod 'Satin', :path => '../'

use_frameworks!

target 'Example-iOS' do
    platform :ios, '12.4'
end

target 'Example-macOS' do
  platform :osx, '10.14'
end

target 'Example-tvOS' do
  platform :tvos, '12.4'
end
