install! 'cocoapods',
         :generate_multiple_pod_projects => true,
         :incremental_installation => true

target 'Example iOS' do
  use_frameworks!
  pod 'Forge', '0.0.3'
  pod 'Satin', :path => "../"
end

target 'Example macOS' do
  use_frameworks!
  pod 'Forge', '0.0.3'
  pod 'Satin', :path => "../"
end

target 'Example tvOS' do
  use_frameworks!
  pod 'Forge', '0.0.3'
  pod 'Satin', :path => "../"
end
