install! 'cocoapods',
         :generate_multiple_pod_projects => true,
         :incremental_installation => true,
         :preserve_pod_file_structure => true

pod 'Forge', :git => 'git@github.com:Hi-Rez/Forge.git'
pod 'Satin', :path => '../'

use_frameworks!

target 'Text-macOS' do
  platform :osx, '10.14'
end

target 'DepthMaterial-macOS' do
  platform :osx, '10.14'
end

target 'DepthMaterial-iOS' do
  platform :ios, '12.4'
end

target 'DepthMaterial-tvOS' do
  platform :tvos, '12.4'
end

target 'PBR-macOS' do
  platform :osx, '10.15'
end

target 'PBR-iOS' do
  platform :ios, '13.0'
end

target 'TextureCompute-macOS' do
  platform :osx, '10.14'
end

target 'TextureCompute-iOS' do
  platform :ios, '12.4'
end

target 'TextureCompute-tvOS' do
  platform :tvos, '12.4'
end

target 'Cubemap-macOS' do
  platform :osx, '10.14'
end

target 'Cubemap-iOS' do
  platform :ios, '12.4'
end

target 'Cubemap-tvOS' do
  platform :tvos, '12.4'
end

target 'Geometry-macOS' do
  platform :osx, '10.14'
end

target 'Geometry-iOS' do
    platform :ios, '12.4'
end

target 'Geometry-tvOS' do
  platform :tvos, '12.4'
end

target 'LiveCode-macOS' do
  platform :osx, '10.14'
end

target 'MatCap-macOS' do
  platform :osx, '10.14'
end

target 'MatCap-iOS' do
    platform :ios, '12.4'
end

target 'MatCap-tvOS' do
  platform :tvos, '12.4'
end

target '3D-iOS' do
    platform :ios, '12.4'
end

target '3D-macOS' do
  platform :osx, '10.14'
end

target '3D-tvOS' do
  platform :tvos, '12.4'
end

target 'Obj-iOS' do
    platform :ios, '12.4'
end

target 'Obj-macOS' do
  platform :osx, '10.14'
end

target 'Obj-tvOS' do
  platform :tvos, '12.4'
end

target '2D-iOS' do
    platform :ios, '12.4'
end

target '2D-macOS' do
  platform :osx, '10.14'
end

target '2D-tvOS' do
  platform :tvos, '12.4'
end
