//
//  Metal+Extensions.swift
//  Example
//
//  Created by Reza Ali on 4/25/23.
//  Copyright © 2023 Hi-Rez. All rights reserved.
//

import Foundation
import Metal

extension MTLPixelFormat {
    var srgb: Bool {
        switch self {
            case .invalid:
                return false
            case .a8Unorm:
                return false
            case .r8Unorm:
                return false
            case .r8Unorm_srgb:
                return true
            case .r8Snorm:
                return false
            case .r8Uint:
                return false
            case .r8Sint:
                return false
            case .r16Unorm:
                return false
            case .r16Snorm:
                return false
            case .r16Uint:
                return false
            case .r16Sint:
                return false
            case .r16Float:
                return false
            case .rg8Unorm:
                return false
            case .rg8Unorm_srgb:
                return true
            case .rg8Snorm:
                return false
            case .rg8Uint:
                return false
            case .rg8Sint:
                return false
            case .b5g6r5Unorm:
                return false
            case .a1bgr5Unorm:
                return false
            case .abgr4Unorm:
                return false
            case .bgr5A1Unorm:
                return false
            case .r32Uint:
                return false
            case .r32Sint:
                return false
            case .r32Float:
                return false
            case .rg16Unorm:
                return false
            case .rg16Snorm:
                return false
            case .rg16Uint:
                return false
            case .rg16Sint:
                return false
            case .rg16Float:
                return false
            case .rgba8Unorm:
                return false
            case .rgba8Unorm_srgb:
                return true
            case .rgba8Snorm:
                return false
            case .rgba8Uint:
                return false
            case .rgba8Sint:
                return false
            case .bgra8Unorm:
                return false
            case .bgra8Unorm_srgb:
                return true
            case .rgb10a2Unorm:
                return false
            case .rgb10a2Uint:
                return false
            case .rg11b10Float:
                return false
            case .rgb9e5Float:
                return false
            case .bgr10a2Unorm:
                return false
            case .bgr10_xr:
                return false
            case .bgr10_xr_srgb:
                return true
            case .rg32Uint:
                return false
            case .rg32Sint:
                return false
            case .rg32Float:
                return false
            case .rgba16Unorm:
                return false
            case .rgba16Snorm:
                return false
            case .rgba16Uint:
                return false
            case .rgba16Sint:
                return false
            case .rgba16Float:
                return false
            case .bgra10_xr:
                return false
            case .bgra10_xr_srgb:
                return true
            case .rgba32Uint:
                return false
            case .rgba32Sint:
                return false
            case .rgba32Float:
                return false
            case .bc1_rgba:
                return false
            case .bc1_rgba_srgb:
                return true
            case .bc2_rgba:
                return false
            case .bc2_rgba_srgb:
                return true
            case .bc3_rgba:
                return false
            case .bc3_rgba_srgb:
                return true
            case .bc4_rUnorm:
                return false
            case .bc4_rSnorm:
                return false
            case .bc5_rgUnorm:
                return false
            case .bc5_rgSnorm:
                return false
            case .bc6H_rgbFloat:
                return false
            case .bc6H_rgbuFloat:
                return false
            case .bc7_rgbaUnorm:
                return false
            case .bc7_rgbaUnorm_srgb:
                return true
            case .pvrtc_rgb_2bpp:
                return false
            case .pvrtc_rgb_2bpp_srgb:
                return true
            case .pvrtc_rgb_4bpp:
                return false
            case .pvrtc_rgb_4bpp_srgb:
                return true
            case .pvrtc_rgba_2bpp:
                return false
            case .pvrtc_rgba_2bpp_srgb:
                return true
            case .pvrtc_rgba_4bpp:
                return false
            case .pvrtc_rgba_4bpp_srgb:
                return true
            case .eac_r11Unorm:
                return false
            case .eac_r11Snorm:
                return false
            case .eac_rg11Unorm:
                return false
            case .eac_rg11Snorm:
                return false
            case .eac_rgba8:
                return false
            case .eac_rgba8_srgb:
                return true
            case .etc2_rgb8:
                return false
            case .etc2_rgb8_srgb:
                return true
            case .etc2_rgb8a1:
                return false
            case .etc2_rgb8a1_srgb:
                return true
            case .astc_4x4_srgb:
                return true
            case .astc_5x4_srgb:
                return true
            case .astc_5x5_srgb:
                return true
            case .astc_6x5_srgb:
                return true
            case .astc_6x6_srgb:
                return true
            case .astc_8x5_srgb:
                return true
            case .astc_8x6_srgb:
                return true
            case .astc_8x8_srgb:
                return true
            case .astc_10x5_srgb:
                return true
            case .astc_10x6_srgb:
                return true
            case .astc_10x8_srgb:
                return true
            case .astc_10x10_srgb:
                return true
            case .astc_12x10_srgb:
                return true
            case .astc_12x12_srgb:
                return true
            case .astc_4x4_ldr:
                return false
            case .astc_5x4_ldr:
                return false
            case .astc_5x5_ldr:
                return false
            case .astc_6x5_ldr:
                return false
            case .astc_6x6_ldr:
                return false
            case .astc_8x5_ldr:
                return false
            case .astc_8x6_ldr:
                return false
            case .astc_8x8_ldr:
                return false
            case .astc_10x5_ldr:
                return false
            case .astc_10x6_ldr:
                return false
            case .astc_10x8_ldr:
                return false
            case .astc_10x10_ldr:
                return false
            case .astc_12x10_ldr:
                return false
            case .astc_12x12_ldr:
                return false
            case .astc_4x4_hdr:
                return false
            case .astc_5x4_hdr:
                return false
            case .astc_5x5_hdr:
                return false
            case .astc_6x5_hdr:
                return false
            case .astc_6x6_hdr:
                return false
            case .astc_8x5_hdr:
                return false
            case .astc_8x6_hdr:
                return false
            case .astc_8x8_hdr:
                return false
            case .astc_10x5_hdr:
                return false
            case .astc_10x6_hdr:
                return false
            case .astc_10x8_hdr:
                return false
            case .astc_10x10_hdr:
                return false
            case .astc_12x10_hdr:
                return false
            case .astc_12x12_hdr:
                return false
            case .gbgr422:
                return false
            case .bgrg422:
                return false
            case .depth16Unorm:
                return false
            case .depth32Float:
                return false
            case .stencil8:
                return false
            case .depth32Float_stencil8:
                return false
            case .x32_stencil8:
                return false
            @unknown default:
                return false
        }
    }
}
